listen              1935;
max_connections     1000;
daemon              off;

http_server {
    enabled on;
    listen 8080;

    # HTTP 静态文件目录
    dir ./objs/nginx/html;
}

http_api {
    enabled on;
    listen 1985;
}

vhost __defaultVhost__ {

    http_hooks {

        enabled on;

        on_publish http://host.docker.internal:8081/hooks/on_publish;

        on_unpublish http://host.docker.internal:8081/hooks/on_unpublish;
    }

    # HTTP-FLV
    http_remux {
        enabled on;
        mount [vhost]/[app]/[stream].flv;
    }

    # HLS
    hls {
        enabled on;
        hls_path ./objs/nginx/html;
        hls_fragment 5;
    }
}